apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-nacos-config
  namespace: ar3d
data:
  SPRING_APPLICATION_JSON: |-
    {
        "spring": {
            "cloud": {
                "nacos": {
                    "discovery": {
                        "registerEnabled": true,
                        "server-addr": "http://nacos.component:30040",
                         "group": "DEFAULT_GROUP",
                         "namespace": ""
                    },
                    "config": {
                        "serverAddr": "http://nacos.component:30040",
                        "fileExtension": "yaml",
                        "group": "DEFAULT_GROUP",
                        "namespace": "",
                        "shared-configs": [
                            {
                                "dataId": "application.yaml",
                                "refresh": true,
                                "namespace": ""
                            },
                            {
                                "dataId": "application-${spring.profiles.active:}.yaml",
                                "refresh": true,
                                "namespace": ""
                            }
                        ]
                    }
                }
            }
        }
    }
