// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFile/BaseFrame.proto

package com.wegood.core.protobuf;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HttpFrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Platform.Model.HttpFrame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 c2sId = 1;</code>
     *
     * <pre>
     * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
     * </pre>
     */
    boolean hasC2SId();
    /**
     * <code>optional int64 c2sId = 1;</code>
     *
     * <pre>
     * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
     * </pre>
     */
    long getC2SId();

    /**
     * <code>optional int64 s2cId = 2;</code>
     *
     * <pre>
     * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
     * </pre>
     */
    boolean hasS2CId();
    /**
     * <code>optional int64 s2cId = 2;</code>
     *
     * <pre>
     * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
     * </pre>
     */
    long getS2CId();

    /**
     * <code>optional string javaProtobufClassC2S = 3;</code>
     *
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    boolean hasJavaProtobufClassC2S();
    /**
     * <code>optional string javaProtobufClassC2S = 3;</code>
     *
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    java.lang.String getJavaProtobufClassC2S();
    /**
     * <code>optional string javaProtobufClassC2S = 3;</code>
     *
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    com.google.protobuf.ByteString
        getJavaProtobufClassC2SBytes();

    /**
     * <code>optional string javaProtobufClassS2C = 4;</code>
     *
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    boolean hasJavaProtobufClassS2C();
    /**
     * <code>optional string javaProtobufClassS2C = 4;</code>
     *
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    java.lang.String getJavaProtobufClassS2C();
    /**
     * <code>optional string javaProtobufClassS2C = 4;</code>
     *
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    com.google.protobuf.ByteString
        getJavaProtobufClassS2CBytes();

    /**
     * <code>optional string url = 5;</code>
     *
     * <pre>
     * 请求url
     * </pre>
     */
    boolean hasUrl();
    /**
     * <code>optional string url = 5;</code>
     *
     * <pre>
     * 请求url
     * </pre>
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 5;</code>
     *
     * <pre>
     * 请求url
     * </pre>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional int32 httpMethod = 6;</code>
     *
     * <pre>
     * http 请求方法
     * </pre>
     */
    boolean hasHttpMethod();
    /**
     * <code>optional int32 httpMethod = 6;</code>
     *
     * <pre>
     * http 请求方法
     * </pre>
     */
    int getHttpMethod();

    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    java.util.List<com.wegood.core.protobuf.Base.StringEntry>
        getHttpHeadersList();
    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    com.wegood.core.protobuf.Base.StringEntry getHttpHeaders(int index);
    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    int getHttpHeadersCount();
    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    java.util.List<? extends com.wegood.core.protobuf.Base.StringEntryOrBuilder>
        getHttpHeadersOrBuilderList();
    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    com.wegood.core.protobuf.Base.StringEntryOrBuilder getHttpHeadersOrBuilder(
        int index);

    /**
     * <code>optional bytes body = 8;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 8;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code Platform.Model.HttpFrame}
   */
  public static final class HttpFrame extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Platform.Model.HttpFrame)
      HttpFrameOrBuilder {
    // Use HttpFrame.newBuilder() to construct.
    private HttpFrame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HttpFrame(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HttpFrame defaultInstance;
    public static HttpFrame getDefaultInstance() {
      return defaultInstance;
    }

    public HttpFrame getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HttpFrame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              c2SId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              s2CId_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              javaProtobufClassC2S_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              javaProtobufClassS2C_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              url_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              httpMethod_ = input.readInt32();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                httpHeaders_ = new java.util.ArrayList<com.wegood.core.protobuf.Base.StringEntry>();
                mutable_bitField0_ |= 0x00000040;
              }
              httpHeaders_.add(input.readMessage(com.wegood.core.protobuf.Base.StringEntry.PARSER, extensionRegistry));
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          httpHeaders_ = java.util.Collections.unmodifiableList(httpHeaders_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wegood.core.protobuf.Base.internal_static_Platform_Model_HttpFrame_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wegood.core.protobuf.Base.internal_static_Platform_Model_HttpFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wegood.core.protobuf.Base.HttpFrame.class, com.wegood.core.protobuf.Base.HttpFrame.Builder.class);
    }

    public static com.google.protobuf.Parser<HttpFrame> PARSER =
        new com.google.protobuf.AbstractParser<HttpFrame>() {
      public HttpFrame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HttpFrame(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HttpFrame> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int C2SID_FIELD_NUMBER = 1;
    private long c2SId_;
    /**
     * <code>optional int64 c2sId = 1;</code>
     *
     * <pre>
     * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
     * </pre>
     */
    public boolean hasC2SId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 c2sId = 1;</code>
     *
     * <pre>
     * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
     * </pre>
     */
    public long getC2SId() {
      return c2SId_;
    }

    public static final int S2CID_FIELD_NUMBER = 2;
    private long s2CId_;
    /**
     * <code>optional int64 s2cId = 2;</code>
     *
     * <pre>
     * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
     * </pre>
     */
    public boolean hasS2CId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 s2cId = 2;</code>
     *
     * <pre>
     * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
     * </pre>
     */
    public long getS2CId() {
      return s2CId_;
    }

    public static final int JAVAPROTOBUFCLASSC2S_FIELD_NUMBER = 3;
    private java.lang.Object javaProtobufClassC2S_;
    /**
     * <code>optional string javaProtobufClassC2S = 3;</code>
     *
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    public boolean hasJavaProtobufClassC2S() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string javaProtobufClassC2S = 3;</code>
     *
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    public java.lang.String getJavaProtobufClassC2S() {
      java.lang.Object ref = javaProtobufClassC2S_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          javaProtobufClassC2S_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string javaProtobufClassC2S = 3;</code>
     *
     * <pre>
     * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    public com.google.protobuf.ByteString
        getJavaProtobufClassC2SBytes() {
      java.lang.Object ref = javaProtobufClassC2S_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaProtobufClassC2S_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JAVAPROTOBUFCLASSS2C_FIELD_NUMBER = 4;
    private java.lang.Object javaProtobufClassS2C_;
    /**
     * <code>optional string javaProtobufClassS2C = 4;</code>
     *
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    public boolean hasJavaProtobufClassS2C() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string javaProtobufClassS2C = 4;</code>
     *
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    public java.lang.String getJavaProtobufClassS2C() {
      java.lang.Object ref = javaProtobufClassS2C_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          javaProtobufClassS2C_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string javaProtobufClassS2C = 4;</code>
     *
     * <pre>
     * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
     * </pre>
     */
    public com.google.protobuf.ByteString
        getJavaProtobufClassS2CBytes() {
      java.lang.Object ref = javaProtobufClassS2C_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaProtobufClassS2C_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 5;
    private java.lang.Object url_;
    /**
     * <code>optional string url = 5;</code>
     *
     * <pre>
     * 请求url
     * </pre>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string url = 5;</code>
     *
     * <pre>
     * 请求url
     * </pre>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string url = 5;</code>
     *
     * <pre>
     * 请求url
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HTTPMETHOD_FIELD_NUMBER = 6;
    private int httpMethod_;
    /**
     * <code>optional int32 httpMethod = 6;</code>
     *
     * <pre>
     * http 请求方法
     * </pre>
     */
    public boolean hasHttpMethod() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 httpMethod = 6;</code>
     *
     * <pre>
     * http 请求方法
     * </pre>
     */
    public int getHttpMethod() {
      return httpMethod_;
    }

    public static final int HTTPHEADERS_FIELD_NUMBER = 7;
    private java.util.List<com.wegood.core.protobuf.Base.StringEntry> httpHeaders_;
    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    public java.util.List<com.wegood.core.protobuf.Base.StringEntry> getHttpHeadersList() {
      return httpHeaders_;
    }
    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    public java.util.List<? extends com.wegood.core.protobuf.Base.StringEntryOrBuilder>
        getHttpHeadersOrBuilderList() {
      return httpHeaders_;
    }
    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    public int getHttpHeadersCount() {
      return httpHeaders_.size();
    }
    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    public com.wegood.core.protobuf.Base.StringEntry getHttpHeaders(int index) {
      return httpHeaders_.get(index);
    }
    /**
     * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
     *
     * <pre>
     * http 请求头
     * </pre>
     */
    public com.wegood.core.protobuf.Base.StringEntryOrBuilder getHttpHeadersOrBuilder(
        int index) {
      return httpHeaders_.get(index);
    }

    public static final int BODY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 8;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes body = 8;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private void initFields() {
      c2SId_ = 0L;
      s2CId_ = 0L;
      javaProtobufClassC2S_ = "";
      javaProtobufClassS2C_ = "";
      url_ = "";
      httpMethod_ = 0;
      httpHeaders_ = java.util.Collections.emptyList();
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getHttpHeadersCount(); i++) {
        if (!getHttpHeaders(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, c2SId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, s2CId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getJavaProtobufClassC2SBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getJavaProtobufClassS2CBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUrlBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, httpMethod_);
      }
      for (int i = 0; i < httpHeaders_.size(); i++) {
        output.writeMessage(7, httpHeaders_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, body_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, c2SId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, s2CId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getJavaProtobufClassC2SBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getJavaProtobufClassS2CBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUrlBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, httpMethod_);
      }
      for (int i = 0; i < httpHeaders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, httpHeaders_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wegood.core.protobuf.Base.HttpFrame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wegood.core.protobuf.Base.HttpFrame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wegood.core.protobuf.Base.HttpFrame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wegood.core.protobuf.Base.HttpFrame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wegood.core.protobuf.Base.HttpFrame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wegood.core.protobuf.Base.HttpFrame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wegood.core.protobuf.Base.HttpFrame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wegood.core.protobuf.Base.HttpFrame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wegood.core.protobuf.Base.HttpFrame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wegood.core.protobuf.Base.HttpFrame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wegood.core.protobuf.Base.HttpFrame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.Model.HttpFrame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Platform.Model.HttpFrame)
        com.wegood.core.protobuf.Base.HttpFrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wegood.core.protobuf.Base.internal_static_Platform_Model_HttpFrame_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wegood.core.protobuf.Base.internal_static_Platform_Model_HttpFrame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wegood.core.protobuf.Base.HttpFrame.class, com.wegood.core.protobuf.Base.HttpFrame.Builder.class);
      }

      // Construct using com.wegood.core.protobuf.Base.HttpFrame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHttpHeadersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        c2SId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        javaProtobufClassC2S_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        javaProtobufClassS2C_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        httpMethod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (httpHeadersBuilder_ == null) {
          httpHeaders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          httpHeadersBuilder_.clear();
        }
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wegood.core.protobuf.Base.internal_static_Platform_Model_HttpFrame_descriptor;
      }

      public com.wegood.core.protobuf.Base.HttpFrame getDefaultInstanceForType() {
        return com.wegood.core.protobuf.Base.HttpFrame.getDefaultInstance();
      }

      public com.wegood.core.protobuf.Base.HttpFrame build() {
        com.wegood.core.protobuf.Base.HttpFrame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wegood.core.protobuf.Base.HttpFrame buildPartial() {
        com.wegood.core.protobuf.Base.HttpFrame result = new com.wegood.core.protobuf.Base.HttpFrame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.c2SId_ = c2SId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s2CId_ = s2CId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.javaProtobufClassC2S_ = javaProtobufClassC2S_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.javaProtobufClassS2C_ = javaProtobufClassS2C_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.httpMethod_ = httpMethod_;
        if (httpHeadersBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            httpHeaders_ = java.util.Collections.unmodifiableList(httpHeaders_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.httpHeaders_ = httpHeaders_;
        } else {
          result.httpHeaders_ = httpHeadersBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wegood.core.protobuf.Base.HttpFrame) {
          return mergeFrom((com.wegood.core.protobuf.Base.HttpFrame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wegood.core.protobuf.Base.HttpFrame other) {
        if (other == com.wegood.core.protobuf.Base.HttpFrame.getDefaultInstance()) return this;
        if (other.hasC2SId()) {
          setC2SId(other.getC2SId());
        }
        if (other.hasS2CId()) {
          setS2CId(other.getS2CId());
        }
        if (other.hasJavaProtobufClassC2S()) {
          bitField0_ |= 0x00000004;
          javaProtobufClassC2S_ = other.javaProtobufClassC2S_;
          onChanged();
        }
        if (other.hasJavaProtobufClassS2C()) {
          bitField0_ |= 0x00000008;
          javaProtobufClassS2C_ = other.javaProtobufClassS2C_;
          onChanged();
        }
        if (other.hasUrl()) {
          bitField0_ |= 0x00000010;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasHttpMethod()) {
          setHttpMethod(other.getHttpMethod());
        }
        if (httpHeadersBuilder_ == null) {
          if (!other.httpHeaders_.isEmpty()) {
            if (httpHeaders_.isEmpty()) {
              httpHeaders_ = other.httpHeaders_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureHttpHeadersIsMutable();
              httpHeaders_.addAll(other.httpHeaders_);
            }
            onChanged();
          }
        } else {
          if (!other.httpHeaders_.isEmpty()) {
            if (httpHeadersBuilder_.isEmpty()) {
              httpHeadersBuilder_.dispose();
              httpHeadersBuilder_ = null;
              httpHeaders_ = other.httpHeaders_;
              bitField0_ = (bitField0_ & ~0x00000040);
              httpHeadersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHttpHeadersFieldBuilder() : null;
            } else {
              httpHeadersBuilder_.addAllMessages(other.httpHeaders_);
            }
          }
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getHttpHeadersCount(); i++) {
          if (!getHttpHeaders(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wegood.core.protobuf.Base.HttpFrame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wegood.core.protobuf.Base.HttpFrame) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long c2SId_ ;
      /**
       * <code>optional int64 c2sId = 1;</code>
       *
       * <pre>
       * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
       * </pre>
       */
      public boolean hasC2SId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 c2sId = 1;</code>
       *
       * <pre>
       * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
       * </pre>
       */
      public long getC2SId() {
        return c2SId_;
      }
      /**
       * <code>optional int64 c2sId = 1;</code>
       *
       * <pre>
       * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
       * </pre>
       */
      public Builder setC2SId(long value) {
        bitField0_ |= 0x00000001;
        c2SId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 c2sId = 1;</code>
       *
       * <pre>
       * 客户端发送给服务端的消息id，可以用当前时间戳赋值。服务端响应时，会将此值原样返回。客户端可以根据此值来判断服务端是否响应客户端的本次请求
       * </pre>
       */
      public Builder clearC2SId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        c2SId_ = 0L;
        onChanged();
        return this;
      }

      private long s2CId_ ;
      /**
       * <code>optional int64 s2cId = 2;</code>
       *
       * <pre>
       * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
       * </pre>
       */
      public boolean hasS2CId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 s2cId = 2;</code>
       *
       * <pre>
       * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
       * </pre>
       */
      public long getS2CId() {
        return s2CId_;
      }
      /**
       * <code>optional int64 s2cId = 2;</code>
       *
       * <pre>
       * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
       * </pre>
       */
      public Builder setS2CId(long value) {
        bitField0_ |= 0x00000002;
        s2CId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 s2cId = 2;</code>
       *
       * <pre>
       * 服务端发送给客户端的消息id，用当前时间戳赋值。客户端需要响应时，应将此值原样返回。服务端可以根据此值来判断客户端是否响应服务端的本次请求
       * </pre>
       */
      public Builder clearS2CId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object javaProtobufClassC2S_ = "";
      /**
       * <code>optional string javaProtobufClassC2S = 3;</code>
       *
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public boolean hasJavaProtobufClassC2S() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string javaProtobufClassC2S = 3;</code>
       *
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public java.lang.String getJavaProtobufClassC2S() {
        java.lang.Object ref = javaProtobufClassC2S_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            javaProtobufClassC2S_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string javaProtobufClassC2S = 3;</code>
       *
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public com.google.protobuf.ByteString
          getJavaProtobufClassC2SBytes() {
        java.lang.Object ref = javaProtobufClassC2S_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          javaProtobufClassC2S_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string javaProtobufClassC2S = 3;</code>
       *
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public Builder setJavaProtobufClassC2S(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        javaProtobufClassC2S_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string javaProtobufClassC2S = 3;</code>
       *
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public Builder clearJavaProtobufClassC2S() {
        bitField0_ = (bitField0_ & ~0x00000004);
        javaProtobufClassC2S_ = getDefaultInstance().getJavaProtobufClassC2S();
        onChanged();
        return this;
      }
      /**
       * <code>optional string javaProtobufClassC2S = 3;</code>
       *
       * <pre>
       * payload的proto对应的java类名。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public Builder setJavaProtobufClassC2SBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        javaProtobufClassC2S_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object javaProtobufClassS2C_ = "";
      /**
       * <code>optional string javaProtobufClassS2C = 4;</code>
       *
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public boolean hasJavaProtobufClassS2C() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string javaProtobufClassS2C = 4;</code>
       *
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public java.lang.String getJavaProtobufClassS2C() {
        java.lang.Object ref = javaProtobufClassS2C_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            javaProtobufClassS2C_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string javaProtobufClassS2C = 4;</code>
       *
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public com.google.protobuf.ByteString
          getJavaProtobufClassS2CBytes() {
        java.lang.Object ref = javaProtobufClassS2C_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          javaProtobufClassS2C_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string javaProtobufClassS2C = 4;</code>
       *
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public Builder setJavaProtobufClassS2C(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        javaProtobufClassS2C_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string javaProtobufClassS2C = 4;</code>
       *
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public Builder clearJavaProtobufClassS2C() {
        bitField0_ = (bitField0_ & ~0x00000008);
        javaProtobufClassS2C_ = getDefaultInstance().getJavaProtobufClassS2C();
        onChanged();
        return this;
      }
      /**
       * <code>optional string javaProtobufClassS2C = 4;</code>
       *
       * <pre>
       * 消息内容的proto s2c。服务端响应时，会复制这个值一并返回
       * </pre>
       */
      public Builder setJavaProtobufClassS2CBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        javaProtobufClassS2C_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>optional string url = 5;</code>
       *
       * <pre>
       * 请求url
       * </pre>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string url = 5;</code>
       *
       * <pre>
       * 请求url
       * </pre>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string url = 5;</code>
       *
       * <pre>
       * 请求url
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string url = 5;</code>
       *
       * <pre>
       * 请求url
       * </pre>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 5;</code>
       *
       * <pre>
       * 请求url
       * </pre>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 5;</code>
       *
       * <pre>
       * 请求url
       * </pre>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        url_ = value;
        onChanged();
        return this;
      }

      private int httpMethod_ ;
      /**
       * <code>optional int32 httpMethod = 6;</code>
       *
       * <pre>
       * http 请求方法
       * </pre>
       */
      public boolean hasHttpMethod() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 httpMethod = 6;</code>
       *
       * <pre>
       * http 请求方法
       * </pre>
       */
      public int getHttpMethod() {
        return httpMethod_;
      }
      /**
       * <code>optional int32 httpMethod = 6;</code>
       *
       * <pre>
       * http 请求方法
       * </pre>
       */
      public Builder setHttpMethod(int value) {
        bitField0_ |= 0x00000020;
        httpMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 httpMethod = 6;</code>
       *
       * <pre>
       * http 请求方法
       * </pre>
       */
      public Builder clearHttpMethod() {
        bitField0_ = (bitField0_ & ~0x00000020);
        httpMethod_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.wegood.core.protobuf.Base.StringEntry> httpHeaders_ =
        java.util.Collections.emptyList();
      private void ensureHttpHeadersIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          httpHeaders_ = new java.util.ArrayList<com.wegood.core.protobuf.Base.StringEntry>(httpHeaders_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.wegood.core.protobuf.Base.StringEntry, com.wegood.core.protobuf.Base.StringEntry.Builder, com.wegood.core.protobuf.Base.StringEntryOrBuilder> httpHeadersBuilder_;

      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public java.util.List<com.wegood.core.protobuf.Base.StringEntry> getHttpHeadersList() {
        if (httpHeadersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(httpHeaders_);
        } else {
          return httpHeadersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public int getHttpHeadersCount() {
        if (httpHeadersBuilder_ == null) {
          return httpHeaders_.size();
        } else {
          return httpHeadersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public com.wegood.core.protobuf.Base.StringEntry getHttpHeaders(int index) {
        if (httpHeadersBuilder_ == null) {
          return httpHeaders_.get(index);
        } else {
          return httpHeadersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public Builder setHttpHeaders(
          int index, com.wegood.core.protobuf.Base.StringEntry value) {
        if (httpHeadersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpHeadersIsMutable();
          httpHeaders_.set(index, value);
          onChanged();
        } else {
          httpHeadersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public Builder setHttpHeaders(
          int index, com.wegood.core.protobuf.Base.StringEntry.Builder builderForValue) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          httpHeaders_.set(index, builderForValue.build());
          onChanged();
        } else {
          httpHeadersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public Builder addHttpHeaders(com.wegood.core.protobuf.Base.StringEntry value) {
        if (httpHeadersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpHeadersIsMutable();
          httpHeaders_.add(value);
          onChanged();
        } else {
          httpHeadersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public Builder addHttpHeaders(
          int index, com.wegood.core.protobuf.Base.StringEntry value) {
        if (httpHeadersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpHeadersIsMutable();
          httpHeaders_.add(index, value);
          onChanged();
        } else {
          httpHeadersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public Builder addHttpHeaders(
          com.wegood.core.protobuf.Base.StringEntry.Builder builderForValue) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          httpHeaders_.add(builderForValue.build());
          onChanged();
        } else {
          httpHeadersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public Builder addHttpHeaders(
          int index, com.wegood.core.protobuf.Base.StringEntry.Builder builderForValue) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          httpHeaders_.add(index, builderForValue.build());
          onChanged();
        } else {
          httpHeadersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public Builder addAllHttpHeaders(
          java.lang.Iterable<? extends com.wegood.core.protobuf.Base.StringEntry> values) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, httpHeaders_);
          onChanged();
        } else {
          httpHeadersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public Builder clearHttpHeaders() {
        if (httpHeadersBuilder_ == null) {
          httpHeaders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          httpHeadersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public Builder removeHttpHeaders(int index) {
        if (httpHeadersBuilder_ == null) {
          ensureHttpHeadersIsMutable();
          httpHeaders_.remove(index);
          onChanged();
        } else {
          httpHeadersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public com.wegood.core.protobuf.Base.StringEntry.Builder getHttpHeadersBuilder(
          int index) {
        return getHttpHeadersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public com.wegood.core.protobuf.Base.StringEntryOrBuilder getHttpHeadersOrBuilder(
          int index) {
        if (httpHeadersBuilder_ == null) {
          return httpHeaders_.get(index);  } else {
          return httpHeadersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public java.util.List<? extends com.wegood.core.protobuf.Base.StringEntryOrBuilder>
           getHttpHeadersOrBuilderList() {
        if (httpHeadersBuilder_ != null) {
          return httpHeadersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(httpHeaders_);
        }
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public com.wegood.core.protobuf.Base.StringEntry.Builder addHttpHeadersBuilder() {
        return getHttpHeadersFieldBuilder().addBuilder(
            com.wegood.core.protobuf.Base.StringEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public com.wegood.core.protobuf.Base.StringEntry.Builder addHttpHeadersBuilder(
          int index) {
        return getHttpHeadersFieldBuilder().addBuilder(
            index, com.wegood.core.protobuf.Base.StringEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .Platform.Model.StringEntry httpHeaders = 7;</code>
       *
       * <pre>
       * http 请求头
       * </pre>
       */
      public java.util.List<com.wegood.core.protobuf.Base.StringEntry.Builder>
           getHttpHeadersBuilderList() {
        return getHttpHeadersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.wegood.core.protobuf.Base.StringEntry, com.wegood.core.protobuf.Base.StringEntry.Builder, com.wegood.core.protobuf.Base.StringEntryOrBuilder>
          getHttpHeadersFieldBuilder() {
        if (httpHeadersBuilder_ == null) {
          httpHeadersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.wegood.core.protobuf.Base.StringEntry, com.wegood.core.protobuf.Base.StringEntry.Builder, com.wegood.core.protobuf.Base.StringEntryOrBuilder>(
                  httpHeaders_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          httpHeaders_ = null;
        }
        return httpHeadersBuilder_;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 8;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes body = 8;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 8;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 8;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000080);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.Model.HttpFrame)
    }

    static {
      defaultInstance = new HttpFrame(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.Model.HttpFrame)
  }

  public interface StringEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Platform.Model.StringEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code Platform.Model.StringEntry}
   */
  public static final class StringEntry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Platform.Model.StringEntry)
      StringEntryOrBuilder {
    // Use StringEntry.newBuilder() to construct.
    private StringEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StringEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StringEntry defaultInstance;
    public static StringEntry getDefaultInstance() {
      return defaultInstance;
    }

    public StringEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StringEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wegood.core.protobuf.Base.internal_static_Platform_Model_StringEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wegood.core.protobuf.Base.internal_static_Platform_Model_StringEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wegood.core.protobuf.Base.StringEntry.class, com.wegood.core.protobuf.Base.StringEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<StringEntry> PARSER =
        new com.google.protobuf.AbstractParser<StringEntry>() {
      public StringEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringEntry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StringEntry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wegood.core.protobuf.Base.StringEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wegood.core.protobuf.Base.StringEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wegood.core.protobuf.Base.StringEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wegood.core.protobuf.Base.StringEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wegood.core.protobuf.Base.StringEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wegood.core.protobuf.Base.StringEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wegood.core.protobuf.Base.StringEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wegood.core.protobuf.Base.StringEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wegood.core.protobuf.Base.StringEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wegood.core.protobuf.Base.StringEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wegood.core.protobuf.Base.StringEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Platform.Model.StringEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Platform.Model.StringEntry)
        com.wegood.core.protobuf.Base.StringEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wegood.core.protobuf.Base.internal_static_Platform_Model_StringEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wegood.core.protobuf.Base.internal_static_Platform_Model_StringEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wegood.core.protobuf.Base.StringEntry.class, com.wegood.core.protobuf.Base.StringEntry.Builder.class);
      }

      // Construct using com.wegood.core.protobuf.Base.StringEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wegood.core.protobuf.Base.internal_static_Platform_Model_StringEntry_descriptor;
      }

      public com.wegood.core.protobuf.Base.StringEntry getDefaultInstanceForType() {
        return com.wegood.core.protobuf.Base.StringEntry.getDefaultInstance();
      }

      public com.wegood.core.protobuf.Base.StringEntry build() {
        com.wegood.core.protobuf.Base.StringEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wegood.core.protobuf.Base.StringEntry buildPartial() {
        com.wegood.core.protobuf.Base.StringEntry result = new com.wegood.core.protobuf.Base.StringEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wegood.core.protobuf.Base.StringEntry) {
          return mergeFrom((com.wegood.core.protobuf.Base.StringEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wegood.core.protobuf.Base.StringEntry other) {
        if (other == com.wegood.core.protobuf.Base.StringEntry.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wegood.core.protobuf.Base.StringEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wegood.core.protobuf.Base.StringEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.Model.StringEntry)
    }

    static {
      defaultInstance = new StringEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.Model.StringEntry)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_HttpFrame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_HttpFrame_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_StringEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_StringEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ProtoFile/BaseFrame.proto\022\016Platform.Mo" +
      "del\"\306\001\n\tHttpFrame\022\r\n\005c2sId\030\001 \001(\003\022\r\n\005s2cI" +
      "d\030\002 \001(\003\022\034\n\024javaProtobufClassC2S\030\003 \001(\t\022\034\n" +
      "\024javaProtobufClassS2C\030\004 \001(\t\022\013\n\003url\030\005 \001(\t" +
      "\022\022\n\nhttpMethod\030\006 \001(\005\0220\n\013httpHeaders\030\007 \003(" +
      "\0132\033.Platform.Model.StringEntry\022\014\n\004body\030\010" +
      " \001(\014\")\n\013StringEntry\022\013\n\003key\030\001 \002(\t\022\r\n\005valu" +
      "e\030\002 \002(\tB\035\n\025com.wegood.core.protobufB\004Base"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Platform_Model_HttpFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Platform_Model_HttpFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Platform_Model_HttpFrame_descriptor,
        new java.lang.String[] { "C2SId", "S2CId", "JavaProtobufClassC2S", "JavaProtobufClassS2C", "Url", "HttpMethod", "HttpHeaders", "Body", });
    internal_static_Platform_Model_StringEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Platform_Model_StringEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Platform_Model_StringEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
