#########################################
##########                     ##########
##########       default       ##########
##########                     ##########
#########################################
info:
  name: ${spring.application.name}

spring:
  http:
    encoding:
      force-response: true

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  #数据库配置
  datasource:
    dynamic:
      p6spy: true
      primary: master
      hikari:
        max-pool-size: 20
        min-idle: 5
        is-auto-commit: true
        idle-timeout: 600000
        connection-timeout: 10000
        max-lifetime: 900000
        connection-test-query: SELECT 1
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${spring.datasource.mysql.master.host}:${spring.datasource.mysql.master.port}/${spring.datasource.mysql.master.database}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&nullDatabaseMeansCurrent=true&tinyInt1isBit=true&rewriteBatchedStatements=TRUE
          username: ${spring.datasource.mysql.master.username}
          password: ${spring.datasource.mysql.master.password}

    mysql:
      master:
        host: 127.0.0.1
        port: 3306
        username: root
        password: 123456

  redis:
    host: 127.0.0.1
    port: 30020
    #  password:
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 5000ms

  flyway:
    #  当迁移时发现目标schema非空，而且带有没有元数据的表时，是否自动执行基准迁移，默认false.
    baseline-on-migrate: true
    baseline-version: 0.1
    locations: classpath:db/mysql
    url: ${spring.datasource.dynamic.datasource.master.url:}
    user: ${spring.datasource.mysql.master.username:}
    password: ${spring.datasource.mysql.master.password:}

security:
  urlAccessSecurityStrategy: NONE
  jwt:
    secret: FtvTa6nt4vfDFVST
  ms:
    secret: FtvTa6nt4vfDFVST

# 本服务监听端口
server:
  max-http-header-size: 10MB

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /${spring.application.name}/actuator
      exposure:
        include: "*"

## 开启Swagger的Basic认证功能,默认是false
knife4j:
  basic:
    enable: false
    username: admin
    password: 123456

feign:
  httpclient:
    connection-timeout: 8000
  compression:
    request:
      min-request-size: 204800

ribbon:
  # 连接超时
  ConnectTimeout: 2000
  # 响应超时
  ReadTimeout: 8000

logging:
  level:
    com:
      ulisesbocchio:
        jasyptspringboot:
          EncryptablePropertySourceConverter: error

#########################################
##########                     ##########
##########      dev-rain       ##########
##########                     ##########
#########################################
---
spring:
  profiles: dev-rain

